from pygame import *

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
GAME_DISPLAY = display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
DISPLAY_SIZE = GAME_DISPLAY.get_size()
DISPLAY_WIDTH = DISPLAY_SIZE[0]
DISPLAY_HEIGHT = DISPLAY_SIZE[1]

ROWS = 100
COLS = 30
CELL_SIZE = 64
MAP_SIZE = (CELL_SIZE*COLS, CELL_SIZE*ROWS)

WATER_CHANCE = 2
START = Vector2(((COLS+1)//2)*CELL_SIZE + (CELL_SIZE+1)//2, (CELL_SIZE+1)//4)

RED = (225, 0, 0)
BLACK = (0, 0, 0)
GREY = (100,100,100)

CIRCLE_RADIUS = 20
SPEED = 5